source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "9.0"
inhibit_all_warnings!
use_frameworks!

target 'CS-IOS_Example' do
  pod 'CS-IOS/CocoaLumberjack', :path => '../'
  pod 'CS-IOS/CollectionController', :path => '../'
  pod 'CS-IOS/TableController', :path => '../'
  pod 'CS-IOS/RefreshControl', :path => '../'
  pod 'CS-IOS/Pager', :path => '../'
  pod 'CS-IOS/AFNetworking', :path => '../'
  pod 'CS-IOS/Reachability', :path => '../'
  pod 'CS-IOS/SDWebImage', :path => '../'
  pod 'CS-IOS/RMessage', :path => '../'
  pod 'CS-IOS/XLPagerTabStrip', :path => '../'
end
