source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "10.0"
inhibit_all_warnings!
use_frameworks!

target 'Example' do
  pod 'Renetik/CocoaLumberjack', :path => '../'
  pod 'Renetik/CollectionController', :path => '../'
  pod 'Renetik/TableController', :path => '../'
  pod 'Renetik/RefreshControl', :path => '../'
  pod 'Renetik/Pager', :path => '../'
  pod 'Renetik/AFNetworking', :path => '../'
  pod 'Renetik/Reachability', :path => '../'
  pod 'Renetik/SDWebImage', :path => '../'
  pod 'Renetik/CSMessage', :path => '../'
  pod 'Renetik/XLPagerTabStrip', :path => '../'
  pod 'XLPagerTabStrip', :git => 'https://github.com/xmartlabs/XLPagerTabStrip', :branch => 'obj-c'
  pod 'Renetik', :testspecs => ['Tests'],:path => '../'
end
