platform :ios, '13.0'
inhibit_all_warnings!
# use_frameworks!
#use_modular_headers!

target 'Renetik_Example' do
    pod 'Renetik', :path => '../'
	
  target 'Renetik_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
#    pod 'FBSnapshotTestCase'
#    pod 'Nimble-Snapshots'
  end
end

 post_install do |installer_representation|
   installer_representation.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
#       config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
#       config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
       if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
       end
     end
   end
 end
