platform :ios, '15.0'
inhibit_all_warnings!
use_frameworks!
#use_modular_headers!
install! 'cocoapods', :disable_input_output_paths => true   # workaround for ignoring changes in development pods

target 'Renetik_Example' do
	pod 'CocoaLumberjack/Swift', '~> 3.4'
	pod 'AFNetworking', '~> 4'
	pod 'Reachability', '~> 3.2'
	pod 'SDWebImage', '~> 5'
	pod 'RMessage', '~> 3'
	pod 'XLPagerTabStrip', '~> 9'
	pod 'ChameleonFramework', '~> 2.1'
	pod 'DZNEmptyDataSet', '~> 1.8'
	pod 'MBProgressHUD', '~> 1.1'
	pod 'DTCoreText', '~> 1.6'
	pod 'IDMPhotoBrowser', :git => 'https://github.com/thiagoperes/IDMPhotoBrowser'
	pod 'TUSafariActivity', '~> 1.0'
	pod 'ARChromeActivity', '~> 1.0'
	
	pod 'RenetikObjc', :path => '../../RenetikObjc'	
  pod 'Renetik', :path => '../'
	

  target 'Renetik_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['SWIFT_VERSION'] = '5.0' if target.name == 'Renetik'
    end
  end

  {
    'AFNetworking/AFNetworking/AFNetworkReachabilityManager.m' => [
      ["#import <netinet6/in6.h>\n", '']
    ],
    'AFNetworking/AFNetworking/AFHTTPSessionManager.m' => [
      ["#import <netinet6/in6.h>\n", '']
    ],
    'HexColors/Sources/HexColors.swift' => [
      ['string.characters.count', 'string.count']
    ]
  }.each do |relative_path, replacements|
    path = installer.sandbox.root + relative_path
    next unless path.exist?

    patched = replacements.reduce(path.read) do |content, (pattern, replacement)|
      content.gsub(pattern, replacement)
    end
    next if patched == path.read

    File.chmod(0644, path.to_s)
    path.open('w') { |file| file.write(patched) }
  end
end
